#!/bin/bash

echo -e "site:http://codepad.co \"$1\""
echo -e "site:http://scribd.com \"$1\""
echo -e "site:http://npmjs.com \"$1\""
echo -e "site:http://npm.runkit.com \"$1\""
echo -e "site:http://libraries.io \"$1\""
echo -e "site:http://ycombinator.com \"$1\""
echo -e "site:http://coggle.it \"$1\""
echo -e "site:http://papaly.com \"$1\""
echo -e "site:http://google.com \"$1\""
echo -e "site:http://trello.com \"$1\""
echo -e "site:http://prezi.com \"$1\""
echo -e "site:http://jsdelivr.net \"$1\""
echo -e "site:http://codepen.io \"$1\""
echo -e "site:http://codeshare.io \"$1\""
echo -e "site:http://sharecode.io \"$1\""
echo -e "site:http://pastebin.com \"$1\""
echo -e "site:http://repl.it \"$1\""
echo -e "site:http://productforums.google.com \"$1\""
echo -e "site:http://gitter.im \"$1\""
echo -e "site:http://bitbucket.org \"$1\""
echo -e "site:*.atlassian.net \"$1\""
echo -e "atlassian.net \"$1\""
echo -e "inurl:gitlab \"$1\""
