#!/bin/bash
#!/bin/bash
RED="\033[31m"
RESET="\033[0m"

echo -e ""
echo -e  "************ Github Dork Links (must be logged in) *******************"
echo -e  ""
echo -e  "${RED}assword${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+password&type=Code&o=desc&s=indexed&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}npmrc _auth${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+npmrc%20_auth&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}dockercfg${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+dockercfg&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}pem private${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+pem%20private&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}id_rsa${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+id_rsa&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}aws_access_key_id${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+aws_access_key_id&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}s3cfg${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+s3cfg&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}htpasswd${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+htpasswd&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}git-credentials${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+git-credentials&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}bashrc password${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+bashrc%20password&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}sshd_config${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+sshd_config&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}xoxp OR xoxb OR xoxa${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+xoxp%20OR%20xoxb%20OR%20xoxa&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}SECRET_KEY${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+SECRET_KEY&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}client_secret${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+client_secret&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}sshd_config${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+sshd_config&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}github_token${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+github_token&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}api_key${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+api_key&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}FTP${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+FTP&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}app_secret${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+app_secret&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}passwd${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+passwd&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}env${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+.env&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}exs${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+.exs&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}beanstalkd.yml${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+beanstalkd.yml&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}deploy.rake${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+deploy.rake&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}mysql${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+mysql&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}credentials${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+credentials&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}PWD${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+PWD&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}deploy.rake${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+deploy.rake&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}bash_history${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+.bash_history&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}sls${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+.sls&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}secrets${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+secrets&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}composer.json${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+composer.json&type=Code&o=desc&s=indexed"
echo -e  ""
echo -e  "${RED}dotfile${RESET}"
echo -e  "https://github.com/search?q=%22$1%22+dotfile&type=Code&o=desc&s=indexed"
echo -e  ""

